# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SF iOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SF iOS
  pod 'Realm'

  target 'SF iOSTests' do
    inherit! :search_paths
    pod 'Realm/Headers'
  end

  target 'SF iOSUITests' do
    inherit! :search_paths
    pod 'Realm/Headers'
  end

end
